apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "externalserver.fullname" . }}
  namespace: {{ include "externalserver.fullname" . }}
  labels:
    {{- include "externalserver.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "externalserver.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        {{- toYaml .Values.podAnnotations | nindent 8 }}
      labels:
        {{- include "externalserver.selectorLabels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ include "externalserver.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ include "externalserver.fullname" . }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          command:
            {{- toYaml .Values.command | nindent 12 }}
          args:
            {{- toYaml .Values.args | nindent 12 }}
          ports:
            - containerPort: {{ .Values.service.port }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          livenessProbe:
            grpc:
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.service.livenessInitialDelaySeconds }}
            periodSeconds: {{ .Values.service.livenessPeriodSeconds }}
          readinessProbe:
            grpc:
              port: {{ .Values.service.port }}
            initialDelaySeconds: {{ .Values.service.readinessInitialDelaySeconds }}
            periodSeconds: {{ .Values.service.readinessPeriodSeconds }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
