apiVersion: v1
kind: Service
metadata:
  name: {{ include "server.fullname" . }}
  namespace: {{ include "server.fullname" . }}
  labels:
    {{- include "server.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
    - name: http
      port: {{ .Values.service.httpPort }}
  selector:
    {{- include "server.selectorLabels" . | nindent 4 }}

---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "secondaryserver.fullname" . }}
  namespace: {{ include "secondaryserver.fullname" . }}
  labels:
    {{- include "secondaryserver.labels" . | nindent 4 }}
spec:
  type: {{ .Values.secondaryserver.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.secondaryserver.service.port }}
  selector:
    {{- include "secondaryserver.selectorLabels" . | nindent 4 }}
